export { default as Header } from './Header';
export { default as Hero } from './Hero';
export { default as Services } from './Services';
export { default as WhyFRP } from './WhyFRP';
export { default as Projects } from './Projects';
export { default as Testimonials } from './Testimonials';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';
export { default as PageHero } from './PageHero';
